In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
daily_calls = pd.read_csv("2023 to 2026(Holiday).csv")

In [4]:
daily_calls

            date  call_count
0     01-01-2023          15
1     02-01-2023          34
2     03-01-2023         231
3     04-01-2023         220
4     05-01-2023         146
...          ...         ...
1103  27-01-2026         895
1104  28-01-2026         930
1105  29-01-2026         872
1106  30-01-2026         930
1107  31-01-2026          61

[1108 rows x 2 columns]

In [5]:
daily = daily_calls.copy()

In [6]:
daily["date"] = pd.to_datetime(daily["date"], format="%d-%m-%Y")

In [7]:
daily['date'].dt.day

0        1
1        2
2        3
3        4
4        5
        ..
1103    27
1104    28
1105    29
1106    30
1107    31
Name: date, Length: 1108, dtype: int32

In [8]:
daily['dayofweek'] = daily['date'].dt.dayofweek
daily['month'] = daily['date'].dt.month
daily['weekofyear'] = daily['date'].dt.isocalendar().week.astype(int)

In [9]:
daily.head()

        date  call_count  dayofweek  month  weekofyear
0 2023-01-01          15          6      1          52
1 2023-01-02          34          0      1           1
2 2023-01-03         231          1      1           1
3 2023-01-04         220          2      1           1
4 2023-01-05         146          3      1           1

In [10]:
daily = daily.sort_values('date').reset_index(drop=True)

In [11]:
daily['lag_1'] = daily["call_count"].shift(1)
daily['lag_7'] = daily["call_count"].shift(7)
daily['lag_14'] = daily["call_count"].shift(14)
daily['lag_21'] = daily["call_count"].shift(21)
daily['lag_28'] = daily["call_count"].shift(28)

In [12]:
daily['roll_mean_7'] = daily['call_count'].rolling(7).mean()
daily['roll_std_7'] = daily['call_count'].rolling(7).std()
daily['roll_mean_14'] = daily['call_count'].rolling(14).mean()
daily['roll_std_14'] = daily['call_count'].rolling(14).std()

In [13]:
daily

,date,call_count,dayofweek,month,weekofyear,lag_1,lag_7,lag_14,lag_21,lag_28,roll_mean_7,roll_std_7,roll_mean_14,roll_std_14
0,2023-01-01,15,6,1,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-01-02,34,0,1,1,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-01-03,231,1,1,1,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-01-04,220,2,1,1,231.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-01-05,146,3,1,1,220.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1103,2026-01-27,895,1,1,5,740.0,901.0,856.0,766.0,512.0,607.857143,401.860850,622.571429,384.256668
1104,2026-01-28,930,2,1,5,895.0,910.0,909.0,701.0,571.0,610.714286,404.429934,624.071429,385.499768
1105,2026-01-29,872,3,1,5,930.0,796.0,853.0,674.0,265.0,621.571429,411.196570,625.428571,386.400094
1106,2026-01-30,930,4,1,5,872.0,862.0,898.0,681.0,280.0,631.285714,418.560515,627.714286,388.226823
1107,2026-01-31,61,5,1,5,930.0,44.0,114.0,68.0,5.0,633.714286,414.615772,623.928571,393.839378

In [14]:
daily.corr()

,date,call_count,dayofweek,month,weekofyear,lag_1,lag_7,lag_14,lag_21,lag_28,roll_mean_7,roll_std_7,roll_mean_14,roll_std_14
date,1.000000,0.238367,-0.002618,0.236297,0.226736,0.240685,0.231581,0.225272,0.217189,0.213350,0.506170,0.514142,0.519871,0.527100
call_count,0.238367,1.000000,-0.679836,0.062708,0.072059,0.477446,0.845270,0.748267,0.644413,0.565999,0.462099,0.419929,0.432069,0.396096
dayofweek,-0.002618,-0.679836,1.000000,-0.001567,0.001089,-0.029404,-0.608617,-0.532791,-0.455270,-0.369791,-0.022293,-0.002184,-0.022540,0.003619
month,0.236297,0.062708,-0.001567,1.000000,0.968057,0.066553,0.112918,0.128600,0.127216,0.104281,0.169478,0.128079,0.225606,0.163889
weekofyear,0.226736,0.072059,0.001089,0.968057,1.000000,0.074165,0.146885,0.149331,0.141678,0.113478,0.197634,0.141975,0.242105,0.161207
lag_1,0.240685,0.477446,-0.029404,0.066553,0.074165,1.000000,0.471368,0.469176,0.458866,0.459672,0.468598,0.432505,0.438170,0.410388
lag_7,0.231581,0.845270,-0.608617,0.112918,0.146885,0.471368,1.000000,0.842142,0.743051,0.639349,0.414779,0.402854,0.456844,0.409588
lag_14,0.225272,0.748267,-0.532791,0.128600,0.149331,0.469176,0.842142,1.000000,0.839024,0.739473,0.335721,0.341980,0.392562,0.373572
lag_21,0.217189,0.644413,-0.455270,0.127216,0.141678,0.458866,0.743051,0.839024,1.000000,0.837159,0.265105,0.289672,0.312284,0.322272
lag_28,0.213350,0.565999,-0.369791,0.104281,0.113478,0.459672,0.639349,0.739473,0.837159,1.000000,0.228813,0.244175,0.258414,0.273373
roll_mean_7,0.506170,0.462099,-0.022293,0.169478,0.197634,0.468598,0.414779,0.335721,0.265105,0.228813,1.000000,0.935824,0.952400,0.902048
roll_std_7,0.514142,0.419929,-0.002184,0.128079,0.141975,0.432505,0.402854,0.341980,0.289672,0.244175,0.935824,1.000000,0.923810,0.966993
roll_mean_14,0.519871,0.432069,-0.022540,0.225606,0.242105,0.438170,0.456844,0.392562,0.312284,0.258414,0.952400,0.923810,1.000000,0.941143
roll_std_14,0.527100,0.396096,0.003619,0.163889,0.161207,0.410388,0.409588,0.373572,0.322272,0.273373,0.902048,0.966993,0.941143,1.000000

In [15]:
train = daily[daily['date'] < "2025-07-01"]
test = daily[daily['date'] >= '2025-07-01']

In [16]:
features = [
    "lag_1","lag_7","lag_21","lag_28","roll_mean_7","roll_mean_14","dayofweek","roll_std_7"
]

In [17]:
target = "call_count"

In [18]:
from xgboost import XGBRegressor

model = XGBRegressor(
    objective="count:poisson",
    n_estimators=380,
    learning_rate=0.06,
    max_depth=2,
    subsample=0.5,
    colsample_bytree=0.9,
    random_state=42
)

In [19]:
model.fit(train[features], train[target])

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.9, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.06, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=2,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=380,
             n_jobs=None, num_parallel_tree=None, ...)

In [20]:
preds = model.predict(test[features])

In [21]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(test[target], preds)
print("MAE:", mae)

MAE: 66.44320203698993

In [22]:
daily["call_count"].mean()

368.5063176895307

In [23]:
preds

array([487.69403 , 515.7453  , 527.90436 , 452.30124 ,  26.355148,
        14.715631, 505.60233 , 537.0526  , 547.1358  , 525.11334 ,
       449.1113  ,  29.906656,  22.14937 , 629.66595 , 641.72876 ,
       621.60474 , 585.8803  , 512.56354 ,  48.55245 ,  18.127073,
       567.03723 , 649.61066 , 655.1175  , 701.0655  , 624.03375 ,
        51.913532,  16.548985, 739.611   , 742.37866 , 782.7107  ,
       757.7178  , 678.2274  ,  49.434456,  33.11201 , 798.1212  ,
       829.372   , 811.5287  , 777.3739  , 710.71246 ,  39.712513,
        43.432335, 752.451   , 818.5569  , 804.5072  , 791.0531  ,
       707.365   ,  52.763184,  22.891987, 736.6225  , 801.04675 ,
       816.622   , 780.0745  , 695.6104  ,  32.565662,  26.522512,
       742.66547 , 830.0485  , 802.666   , 767.549   , 663.2752  ,
        34.595135,  20.910337, 739.1178  , 722.60956 , 629.99963 ,
       564.15906 ,  79.986885,  15.989006, 434.84238 , 773.0719  ,
       756.6022  , 720.62244 , 640.3462  ,  56.157627,  17.563168,
       576.3451  , 642.79205 , 614.21545 , 615.4421  , 547.4819  ,
        45.974804, 418.39005 , 844.7731  , 705.2385  , 688.88293 ,
       626.65    ,  87.815315,  21.689024, 588.034   , 679.62885 ,
       639.15894 , 577.2216  , 551.69476 ,  57.342045,  17.954952,
       673.58246 , 726.47314 , 723.722   , 704.82837 , 626.5625  ,
        67.94561 ,  32.213333, 635.7636  , 784.05994 , 734.74817 ,
       637.6657  , 605.649   ,  49.186897,  20.054338, 703.28204 ,
       731.4842  , 737.3384  , 727.3678  , 680.24225 ,  55.646973,
        62.28663 , 740.8266  , 794.3166  , 766.46606 , 758.53516 ,
       685.6232  ,  65.25948 ,  42.283157, 785.90753 , 794.8971  ,
       812.5153  , 760.60144 , 667.75354 ,  47.68947 ,  29.271933,
       714.26685 , 740.7401  , 705.4675  , 633.9639  , 560.8438  ,
        73.624146,  27.464634, 609.9726  , 634.65204 , 623.4609  ,
       613.4948  , 578.6293  ,  51.153633,  25.163288, 652.32544 ,
       743.79425 , 756.2274  , 649.5484  ,  82.88624 ,  38.827488,
       479.7856  , 784.31683 , 775.83264 , 759.888   , 664.8147  ,
        48.664345,  36.525784, 795.57776 , 826.66583 , 817.0353  ,
       788.7871  , 703.8292  ,  55.786083,  42.2372  , 792.41486 ,
       820.8712  , 806.7091  , 789.7837  , 697.70123 ,  60.372086,
        27.081446, 619.9075  , 600.267   , 475.6301  ,  58.190697,
        21.799828, 271.02448 , 355.84018 , 386.3091  , 280.20123 ,
        60.13147 ,  29.606596, 446.78586 , 617.5684  , 646.4773  ,
       654.4338  , 630.7123  ,  52.87816 ,  42.68896 , 722.5434  ,
       745.8289  , 919.968   , 743.75165 , 693.6873  ,  83.818535,
        54.19353 , 741.0188  , 800.77747 , 814.2222  , 804.5582  ,
       751.19763 ,  70.33176 ,  21.001509, 715.3542  , 802.6832  ,
       794.5113  , 782.0716  , 711.9882  ,  65.42815 ], dtype=float32)

In [24]:
test[target]

899     509
900     571
901     553
902      52
903      10
       ...
1103    895
1104    930
1105    872
1106    930
1107     61
Name: call_count, Length: 209, dtype: int64

In [25]:
daily

,date,call_count,dayofweek,month,weekofyear,lag_1,lag_7,lag_14,lag_21,lag_28,roll_mean_7,roll_std_7,roll_mean_14,roll_std_14
0,2023-01-01,15,6,1,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-01-02,34,0,1,1,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-01-03,231,1,1,1,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-01-04,220,2,1,1,231.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-01-05,146,3,1,1,220.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1103,2026-01-27,895,1,1,5,740.0,901.0,856.0,766.0,512.0,607.857143,401.860850,622.571429,384.256668
1104,2026-01-28,930,2,1,5,895.0,910.0,909.0,701.0,571.0,610.714286,404.429934,624.071429,385.499768
1105,2026-01-29,872,3,1,5,930.0,796.0,853.0,674.0,265.0,621.571429,411.196570,625.428571,386.400094
1106,2026-01-30,930,4,1,5,872.0,862.0,898.0,681.0,280.0,631.285714,418.560515,627.714286,388.226823
1107,2026-01-31,61,5,1,5,930.0,44.0,114.0,68.0,5.0,633.714286,414.615772,623.928571,393.839378

In [26]:
# remove weekday rows where call_count < 200
df = daily[~((daily['dayofweek'] <= 4) & (daily['call_count'] < 200))]

# sort by date
df = df.sort_values('date')

df

,date,call_count,dayofweek,month,weekofyear,lag_1,lag_7,lag_14,lag_21,lag_28,roll_mean_7,roll_std_7,roll_mean_14,roll_std_14
0,2023-01-01,15,6,1,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-01-03,231,1,1,1,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-01-04,220,2,1,1,231.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2023-01-07,60,5,1,1,154.0,NaN,NaN,NaN,NaN,122.857143,87.670650,NaN,NaN
7,2023-01-08,24,6,1,1,60.0,15.0,NaN,NaN,NaN,124.142857,85.872830,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1103,2026-01-27,895,1,1,5,740.0,901.0,856.0,766.0,512.0,607.857143,401.860850,622.571429,384.256668
1104,2026-01-28,930,2,1,5,895.0,910.0,909.0,701.0,571.0,610.714286,404.429934,624.071429,385.499768
1105,2026-01-29,872,3,1,5,930.0,796.0,853.0,674.0,265.0,621.571429,411.196570,625.428571,386.400094
1106,2026-01-30,930,4,1,5,872.0,862.0,898.0,681.0,280.0,631.285714,418.560515,627.714286,388.226823
1107,2026-01-31,61,5,1,5,930.0,44.0,114.0,68.0,5.0,633.714286,414.615772,623.928571,393.839378

In [27]:
train = df[df['date'] < "2025-07-01"]
test = df[df['date'] >= '2025-07-01']

In [217]:
from xgboost import XGBRegressor

model = XGBRegressor(
    objective="count:poisson",
    n_estimators=382,
    learning_rate=0.06,
    max_depth=2,
    subsample=0.5,
    colsample_bytree=0.9,
    random_state=42
)

In [219]:
model.fit(train[features], train[target])

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.9, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.06, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=2,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=382,
             n_jobs=None, num_parallel_tree=None, ...)

In [220]:
preds = model.predict(test[features])

In [225]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(test[target], preds)
print("MAE:", mae)

MAE: 64.29683706495497

In [227]:
preds

array([501.6751  , 526.71655 , 542.53815 ,  27.329514,  15.309443,
       515.3483  , 553.49445 , 573.68085 , 549.69226 , 519.7195  ,
        30.050585,  21.947931, 633.55804 , 654.5211  , 630.25836 ,
       597.3771  , 516.3428  ,  50.64921 ,  19.354422, 551.7416  ,
       673.0283  , 646.649   , 711.622   , 626.20105 ,  49.58109 ,
        17.426374, 757.00385 , 768.9579  , 804.60925 , 775.85004 ,
       700.9181  ,  51.71279 ,  34.73207 , 788.53064 , 847.7471  ,
       811.54535 , 803.5426  , 716.2938  ,  44.539234,  45.737843,
       771.7964  , 832.1469  , 784.53265 , 810.59045 , 706.6958  ,
        67.23961 ,  21.548996, 753.7883  , 840.2146  , 825.13544 ,
       798.9376  , 676.1079  ,  33.44274 ,  27.62387 , 755.2656  ,
       837.55133 , 780.94507 , 769.6817  , 679.9961  ,  34.121   ,
        20.129498, 737.3742  , 734.15    , 631.6962  , 563.62585 ,
        75.00816 ,  15.9509  , 491.22406 , 747.4688  , 759.0265  ,
       733.26105 , 651.6145  ,  50.59584 ,  16.607006, 678.1446  ,
       644.6227  , 612.20465 , 623.733   , 559.4344  ,  41.632767,
       513.93774 , 871.78107 , 699.4621  , 702.2637  , 619.50323 ,
        84.31327 ,  20.408255, 629.42224 , 694.5856  , 632.3638  ,
       591.5173  , 552.76544 ,  51.400906,  18.941408, 677.90533 ,
       713.5465  , 722.46796 , 704.69525 , 632.85095 ,  63.635777,
        33.826378, 752.8077  , 777.32684 , 730.3769  , 659.41437 ,
       606.0049  ,  44.671406,  18.568066, 700.26965 , 725.65436 ,
       732.836   , 744.5291  , 688.26306 ,  63.060883,  60.88317 ,
       730.06946 , 788.54266 , 735.9558  , 759.35486 , 684.0444  ,
        68.59032 ,  47.01589 , 755.213   , 817.1366  , 804.9757  ,
       765.5653  , 644.04565 ,  45.799683,  24.228043, 695.75775 ,
       713.38354 , 666.2657  , 647.9006  , 556.1262  ,  81.34457 ,
        27.842413, 611.2927  , 640.3358  , 620.1576  , 617.01355 ,
       589.66455 ,  47.441936,  24.94004 , 649.3322  , 753.48035 ,
       752.6383  , 651.5511  ,  82.12772 ,  39.451984, 446.5092  ,
       787.1636  , 784.55695 , 757.8439  , 668.9901  ,  47.915928,
        37.851418, 744.56036 , 837.9304  , 830.96173 , 800.0298  ,
       719.6174  ,  58.428894,  46.69644 , 777.50183 , 839.80444 ,
       800.4766  , 807.8181  , 691.9357  ,  60.18643 ,  26.38361 ,
       648.9435  , 597.6275  ,  72.95686 ,  36.886734, 308.1626  ,
       355.8553  , 409.25287 , 340.0848  ,  69.61151 ,  30.10154 ,
       540.4403  , 604.18823 , 646.39343 , 656.03845 , 613.15234 ,
        46.023937,  35.577034, 717.6357  , 725.6685  , 881.94507 ,
       742.879   , 717.38696 ,  93.92281 ,  53.51737 , 745.8727  ,
       835.27563 , 773.8903  , 784.8028  , 741.13367 ,  73.13007 ,
        23.126074, 748.55524 , 843.6089  , 784.53265 , 757.3114  ,
       700.49976 ,  67.84784 ], dtype=float32)

In [34]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=1400,
    max_depth=10,
    min_samples_split=10,
    min_samples_leaf=4,
    max_features="sqrt",
    bootstrap=True,
    random_state=42,
    n_jobs=-1
)

In [35]:
rf.fit(train[features], train[target])

RandomForestRegressor(max_depth=10, max_features='sqrt', min_samples_leaf=4,
                      min_samples_split=10, n_estimators=1400, n_jobs=-1,
                      random_state=42)

In [36]:
preds = rf.predict(test[features])

In [37]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(test[target], preds)
print("MAE:", mae)

MAE: 91.45149505561405

In [38]:
from sklearn.tree import DecisionTreeRegressor

In [39]:
model = DecisionTreeRegressor(
    max_depth=4,
    min_samples_split=6,
    min_samples_leaf=3,
    max_features='sqrt',
    random_state=42
)

In [40]:
model.fit(train[features], train[target])

DecisionTreeRegressor(max_depth=4, max_features='sqrt', min_samples_leaf=3,
                      min_samples_split=6, random_state=42)

In [41]:
preds = model.predict(test[features])

In [42]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(test[target], preds)
print("MAE:", mae)

MAE: 78.73437481438341

In [43]:
daily_calls

            date  call_count
0     01-01-2023          15
1     02-01-2023          34
2     03-01-2023         231
3     04-01-2023         220
4     05-01-2023         146
...          ...         ...
1103  27-01-2026         895
1104  28-01-2026         930
1105  29-01-2026         872
1106  30-01-2026         930
1107  31-01-2026          61

[1108 rows x 2 columns]

In [44]:
df

,date,call_count,dayofweek,month,weekofyear,lag_1,lag_7,lag_14,lag_21,lag_28,roll_mean_7,roll_std_7,roll_mean_14,roll_std_14
0,2023-01-01,15,6,1,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-01-03,231,1,1,1,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-01-04,220,2,1,1,231.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2023-01-07,60,5,1,1,154.0,NaN,NaN,NaN,NaN,122.857143,87.670650,NaN,NaN
7,2023-01-08,24,6,1,1,60.0,15.0,NaN,NaN,NaN,124.142857,85.872830,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1103,2026-01-27,895,1,1,5,740.0,901.0,856.0,766.0,512.0,607.857143,401.860850,622.571429,384.256668
1104,2026-01-28,930,2,1,5,895.0,910.0,909.0,701.0,571.0,610.714286,404.429934,624.071429,385.499768
1105,2026-01-29,872,3,1,5,930.0,796.0,853.0,674.0,265.0,621.571429,411.196570,625.428571,386.400094
1106,2026-01-30,930,4,1,5,872.0,862.0,898.0,681.0,280.0,631.285714,418.560515,627.714286,388.226823
1107,2026-01-31,61,5,1,5,930.0,44.0,114.0,68.0,5.0,633.714286,414.615772,623.928571,393.839378

In [231]:
df.to_csv("main.csv", index = False)