In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
daily_calls = pd.read_csv("2023 to 2026(all).csv")

In [4]:
daily_calls

            date  call_count
0     01-01-2023          15
1     02-01-2023          34
2     03-01-2023         231
3     04-01-2023         220
4     05-01-2023         146
...          ...         ...
1119  27-01-2026         895
1120  28-01-2026         930
1121  29-01-2026         872
1122  30-01-2026         930
1123  31-01-2026          61

[1124 rows x 2 columns]

In [5]:
daily_calls.head()

         date  call_count
0  01-01-2023          15
1  02-01-2023          34
2  03-01-2023         231
3  04-01-2023         220
4  05-01-2023         146

In [6]:
daily = daily_calls.copy()

In [7]:
daily["date"] = pd.to_datetime(daily["date"], format="%d-%m-%Y")

In [8]:
daily["date"].dt.day

0        1
1        2
2        3
3        4
4        5
        ..
1119    27
1120    28
1121    29
1122    30
1123    31
Name: date, Length: 1124, dtype: int32

In [9]:
daily['dayofweek'] = daily['date'].dt.dayofweek
daily['month'] = daily['date'].dt.month
daily['weekofyear'] = daily['date'].dt.isocalendar().week.astype(int)

In [10]:
daily.head()

        date  call_count  dayofweek  month  weekofyear
0 2023-01-01          15          6      1          52
1 2023-01-02          34          0      1           1
2 2023-01-03         231          1      1           1
3 2023-01-04         220          2      1           1
4 2023-01-05         146          3      1           1

In [11]:
daily = daily.sort_values('date').reset_index(drop=True)

In [12]:
daily['lag_1'] = daily["call_count"].shift(1)
daily['lag_7'] = daily['call_count'].shift(7)
daily['lag_14'] = daily['call_count'].shift(14)
daily['lag_21'] = daily['call_count'].shift(21)
daily['lag_28'] = daily['call_count'].shift(28)

In [13]:
daily['roll_mean_7'] = daily['call_count'].rolling(7).mean()
daily['roll_std_7']= daily['call_count'].rolling(7).std()

daily['roll_mean_14']= daily['call_count'].rolling(14).mean()
daily['roll_std_14'] = daily['call_count'].rolling(14).std()

In [14]:
daily

,date,call_count,dayofweek,month,weekofyear,lag_1,lag_7,lag_14,lag_21,lag_28,roll_mean_7,roll_std_7,roll_mean_14,roll_std_14
0,2023-01-01,15,6,1,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-01-02,34,0,1,1,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-01-03,231,1,1,1,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-01-04,220,2,1,1,231.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-01-05,146,3,1,1,220.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1119,2026-01-27,895,1,1,5,740.0,901.0,856.0,766.0,571.0,607.857143,401.860850,622.571429,384.256668
1120,2026-01-28,930,2,1,5,895.0,910.0,909.0,701.0,265.0,610.714286,404.429934,624.071429,385.499768
1121,2026-01-29,872,3,1,5,930.0,796.0,853.0,674.0,10.0,621.571429,411.196570,625.428571,386.400094
1122,2026-01-30,930,4,1,5,872.0,862.0,898.0,681.0,280.0,631.285714,418.560515,627.714286,388.226823
1123,2026-01-31,61,5,1,5,930.0,44.0,114.0,68.0,5.0,633.714286,414.615772,623.928571,393.839378

In [15]:
import holidays

# create US holidays for required years
us_holidays = holidays.US(years=[2023, 2024, 2025, 2026])
print(us_holidays)

# create holiday column
daily["is_us_holiday"] = daily["date"].dt.date.isin(us_holidays).astype(int)

{datetime.date(2024, 1, 1): "New Year's Day", datetime.date(2024, 5, 27): 'Memorial Day', datetime.date(2024, 6, 19): 'Juneteenth National Independence Day', datetime.date(2024, 7, 4): 'Independence Day', datetime.date(2024, 9, 2): 'Labor Day', datetime.date(2024, 11, 28): 'Thanksgiving Day', datetime.date(2024, 12, 25): 'Christmas Day', datetime.date(2024, 1, 15): 'Martin Luther King Jr. Day', datetime.date(2024, 2, 19): "Washington's Birthday", datetime.date(2024, 10, 14): 'Columbus Day', datetime.date(2024, 11, 11): 'Veterans Day', datetime.date(2025, 1, 1): "New Year's Day", datetime.date(2025, 5, 26): 'Memorial Day', datetime.date(2025, 6, 19): 'Juneteenth National Independence Day', datetime.date(2025, 7, 4): 'Independence Day', datetime.date(2025, 9, 1): 'Labor Day', datetime.date(2025, 11, 27): 'Thanksgiving Day', datetime.date(2025, 12, 25): 'Christmas Day', datetime.date(2025, 1, 20): 'Martin Luther King Jr. Day', datetime.date(2025, 2, 17): "Washington's Birthday", datetime.date(2025, 10, 13): 'Columbus Day', datetime.date(2025, 11, 11): 'Veterans Day', datetime.date(2026, 1, 1): "New Year's Day", datetime.date(2026, 5, 25): 'Memorial Day', datetime.date(2026, 6, 19): 'Juneteenth National Independence Day', datetime.date(2026, 7, 4): 'Independence Day', datetime.date(2026, 7, 3): 'Independence Day (observed)', datetime.date(2026, 9, 7): 'Labor Day', datetime.date(2026, 11, 26): 'Thanksgiving Day', datetime.date(2026, 12, 25): 'Christmas Day', datetime.date(2026, 1, 19): 'Martin Luther King Jr. Day', datetime.date(2026, 2, 16): "Washington's Birthday", datetime.date(2026, 10, 12): 'Columbus Day', datetime.date(2026, 11, 11): 'Veterans Day', datetime.date(2023, 1, 1): "New Year's Day", datetime.date(2023, 1, 2): "New Year's Day (observed)", datetime.date(2023, 5, 29): 'Memorial Day', datetime.date(2023, 6, 19): 'Juneteenth National Independence Day', datetime.date(2023, 7, 4): 'Independence Day', datetime.date(2023, 9, 4): 'Labor Day', datetime.date(2023, 11, 23): 'Thanksgiving Day', datetime.date(2023, 12, 25): 'Christmas Day', datetime.date(2023, 1, 16): 'Martin Luther King Jr. Day', datetime.date(2023, 2, 20): "Washington's Birthday", datetime.date(2023, 10, 9): 'Columbus Day', datetime.date(2023, 11, 11): 'Veterans Day', datetime.date(2023, 11, 10): 'Veterans Day (observed)'}

In [16]:
daily

,date,call_count,dayofweek,month,weekofyear,lag_1,lag_7,lag_14,lag_21,lag_28,roll_mean_7,roll_std_7,roll_mean_14,roll_std_14,is_us_holiday
0,2023-01-01,15,6,1,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,2023-01-02,34,0,1,1,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,2023-01-03,231,1,1,1,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,2023-01-04,220,2,1,1,231.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,2023-01-05,146,3,1,1,220.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1119,2026-01-27,895,1,1,5,740.0,901.0,856.0,766.0,571.0,607.857143,401.860850,622.571429,384.256668,0
1120,2026-01-28,930,2,1,5,895.0,910.0,909.0,701.0,265.0,610.714286,404.429934,624.071429,385.499768,0
1121,2026-01-29,872,3,1,5,930.0,796.0,853.0,674.0,10.0,621.571429,411.196570,625.428571,386.400094,0
1122,2026-01-30,930,4,1,5,872.0,862.0,898.0,681.0,280.0,631.285714,418.560515,627.714286,388.226823,0
1123,2026-01-31,61,5,1,5,930.0,44.0,114.0,68.0,5.0,633.714286,414.615772,623.928571,393.839378,0

In [17]:
daily.corr()

,date,call_count,dayofweek,month,weekofyear,lag_1,lag_7,lag_14,lag_21,lag_28,roll_mean_7,roll_std_7,roll_mean_14,roll_std_14,is_us_holiday
date,1.000000,0.228247,-0.000223,0.235182,0.225890,0.230500,0.221290,0.214733,0.206390,0.202223,0.481444,0.510031,0.497068,0.526061,0.003666
call_count,0.228247,1.000000,-0.660549,0.053146,0.061529,0.482068,0.858239,0.800978,0.743159,0.727079,0.446167,0.417878,0.410057,0.394746,-0.080294
dayofweek,-0.000223,-0.660549,1.000000,-0.003663,-0.001414,-0.024061,-0.653670,-0.641821,-0.630737,-0.613076,-0.002434,-0.010829,-0.004029,-0.005446,-0.151595
month,0.235182,0.053146,-0.003663,1.000000,0.968623,0.056916,0.109012,0.141987,0.139596,0.118186,0.146460,0.126649,0.215077,0.171908,0.012609
weekofyear,0.225890,0.061529,-0.001414,0.968623,1.000000,0.063539,0.135459,0.140273,0.133501,0.105390,0.179094,0.139491,0.240634,0.174005,0.033064
lag_1,0.230500,0.482068,-0.024061,0.056916,0.063539,1.000000,0.428689,0.387858,0.355439,0.358286,0.467179,0.428695,0.430180,0.403649,-0.111400
lag_7,0.221290,0.858239,-0.653670,0.109012,0.135459,0.428689,1.000000,0.855405,0.796935,0.739824,0.402686,0.401745,0.444992,0.407822,0.072062
lag_14,0.214733,0.800978,-0.641821,0.141987,0.140273,0.387858,0.855405,1.000000,0.852587,0.794274,0.315866,0.339045,0.378172,0.370660,0.070271
lag_21,0.206390,0.743159,-0.630737,0.139596,0.133501,0.355439,0.796935,0.852587,1.000000,0.850964,0.236275,0.291675,0.288378,0.319468,0.094082
lag_28,0.202223,0.727079,-0.613076,0.118186,0.105390,0.358286,0.739824,0.794274,0.850964,1.000000,0.205956,0.250243,0.232442,0.274418,0.063691
roll_mean_7,0.481444,0.446167,-0.002434,0.146460,0.179094,0.467179,0.402686,0.315866,0.236275,0.205956,1.000000,0.916986,0.945830,0.876851,-0.060276
roll_std_7,0.510031,0.417878,-0.010829,0.126649,0.139491,0.428695,0.401745,0.339045,0.291675,0.250243,0.916986,1.000000,0.908001,0.962300,-0.004887
roll_mean_14,0.497068,0.410057,-0.004029,0.215077,0.240634,0.430180,0.444992,0.378172,0.288378,0.232442,0.945830,0.908001,1.000000,0.922971,-0.039055
roll_std_14,0.526061,0.394746,-0.005446,0.171908,0.174005,0.403649,0.407822,0.370660,0.319468,0.274418,0.876851,0.962300,0.922971,1.000000,-0.006745
is_us_holiday,0.003666,-0.080294,-0.151595,0.012609,0.033064,-0.111400,0.072062,0.070271,0.094082,0.063691,-0.060276,-0.004887,-0.039055,-0.006745,1.000000

In [18]:
train = daily[daily["date"] < "2025-07-01"]
test = daily[daily["date"] >= '2025-07-01']

In [19]:
features = [
    "lag_1","lag_7","lag_21","lag_28","roll_mean_7","roll_mean_14","dayofweek","is_us_holiday","roll_std_7"
]

In [20]:
target = "call_count"

In [21]:
from xgboost import XGBRegressor

model = XGBRegressor(
    objective="count:poisson",
    n_estimators=385,
    learning_rate=0.06,
    max_depth=2,
    subsample=0.8,
    colsample_bytree=0.9,
    random_state=42
)

In [22]:
model.fit(train[features], train[target])

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.9, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.06, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=2,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=385,
             n_jobs=None, num_parallel_tree=None, ...)

In [23]:
preds = model.predict(test[features])

In [24]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(test[target], preds)
print("MAE:", mae)

MAE: 81.41482217289577

In [42]:
import pickle

with open("call_volume_ALL_model.pkl", "wb") as file:
    pickle.dump(model, file)

In [44]:
daily["call_count"].mean()

364.5275800711744

In [46]:
preds

array([500.39383 , 526.82983 , 537.0035  , 388.80597 ,  24.364918,
        16.186913, 499.5856  , 541.06354 , 571.8717  , 519.181   ,
       474.43976 ,  22.36835 ,  22.103638, 630.7878  , 658.973   ,
       637.5633  , 597.3475  , 512.97797 ,  58.603146,  19.817598,
       548.1122  , 666.3114  , 688.10425 , 688.4134  , 687.4729  ,
        63.50228 ,  18.497158, 734.85785 , 764.054   , 805.29706 ,
       767.04956 , 666.8047  ,  42.67156 ,  35.614265, 742.8879  ,
       810.916   , 785.7026  , 767.04956 , 703.5467  ,  33.662136,
        50.5127  , 723.9764  , 785.4576  , 805.29706 , 773.28827 ,
       703.2713  ,  64.08865 ,  23.562326, 633.6339  , 829.1992  ,
       805.29706 , 773.28827 , 695.4827  ,  39.33203 ,  32.41043 ,
       614.05145 , 785.4576  , 805.29706 , 767.04956 , 699.5908  ,
        33.422512,  27.103357, 264.55753 , 670.51825 , 653.7089  ,
       591.64734 , 551.6148  ,  30.818403,  20.107218, 528.5628  ,
       789.41437 , 780.5605  , 749.6883  , 691.2785  ,  32.83332 ,
        19.853403, 600.2284  , 652.48724 , 617.95605 , 616.5439  ,
       577.54456 ,  28.179337, 303.8962  , 742.5575  , 737.07227 ,
       717.3008  , 650.2503  , 117.27243 ,  20.877634, 504.83865 ,
       645.7853  , 642.4023  , 579.2565  , 572.0749  ,  62.005733,
        19.617098, 615.4122  , 719.122   , 732.9087  , 709.433   ,
       648.1864  ,  68.03334 ,  44.696175, 298.24707 , 804.0393  ,
       728.6623  , 662.5965  , 591.44226 ,  54.89311 ,  13.091037,
       683.5113  , 732.26276 , 733.6118  , 743.6176  , 701.72705 ,
        52.87531 ,  48.555702, 690.68146 , 757.4476  , 743.3613  ,
       715.1908  , 660.8932  ,  83.9597  ,  54.64696 , 741.0764  ,
       817.4951  , 785.7026  , 718.62976 , 644.9968  ,  39.376694,
        23.535822, 692.36316 , 376.2323  , 676.52356 , 656.8839  ,
       579.85065 ,  73.86231 ,  29.902735, 592.7718  , 650.4503  ,
       634.33374 , 618.15643 , 609.8958  ,  65.72333 ,  28.616314,
       648.2108  , 755.539   , 778.4092  , 361.68106 , 416.62698 ,
        66.10965 ,  20.086298, 586.81445 , 693.9182  , 688.9036  ,
       529.02496 , 680.24646 ,  37.628315,  40.040695, 739.11566 ,
       816.666   , 798.468   , 773.28827 , 712.8273  ,  45.807457,
        37.717937, 684.36993 , 785.4576  , 805.29706 , 749.4928  ,
       658.3477  ,  69.72881 ,  21.615528, 640.0305  , 606.9262  ,
       453.78534 , 156.86635 ,  82.891655,  28.340271,  15.238905,
       177.36398 , 253.69296 , 261.81357 , 133.31319 , 216.52501 ,
        41.201744,  38.302265, 319.52536 , 535.7832  , 650.6988  ,
       535.4246  , 661.15765 ,  44.820805,  22.861137, 692.68115 ,
       797.9146  , 810.55725 , 741.1252  , 712.357   ,  70.68855 ,
        57.252186, 364.9825  , 783.6772  , 803.7265  , 630.67773 ,
       679.1611  ,  75.23792 ,  21.284576, 642.2565  , 791.83014 ,
       803.8116  , 700.6672  , 711.5124  ,  59.339848], dtype=float32)

In [48]:
test[target].tail(10)

1114    796
1115    862
1116     44
1117      8
1118    740
1119    895
1120    930
1121    872
1122    930
1123     61
Name: call_count, dtype: int64

In [50]:
from sklearn.ensemble import RandomForestRegressor

In [51]:
model = RandomForestRegressor(n_estimators=350, random_state=42)

In [52]:
model.fit(train[features], train[target])

RandomForestRegressor(n_estimators=350, random_state=42)

In [53]:
preds = model.predict(test[features])

In [54]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(test[target], preds)
print("MAE:", mae)

MAE: 83.67546061415219

In [57]:
df= daily[~(
    (daily["dayofweek"].isin([0,1,2,3,4])) & 
    (daily["call_count"] < 200) & 
    (daily["is_us_holiday"] == 0)
)]

In [58]:
df

,date,call_count,dayofweek,month,weekofyear,lag_1,lag_7,lag_14,lag_21,lag_28,roll_mean_7,roll_std_7,roll_mean_14,roll_std_14,is_us_holiday
0,2023-01-01,15,6,1,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,2023-01-02,34,0,1,1,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,2023-01-03,231,1,1,1,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,2023-01-04,220,2,1,1,231.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
6,2023-01-07,60,5,1,1,154.0,NaN,NaN,NaN,NaN,122.857143,87.670650,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1119,2026-01-27,895,1,1,5,740.0,901.0,856.0,766.0,571.0,607.857143,401.860850,622.571429,384.256668,0
1120,2026-01-28,930,2,1,5,895.0,910.0,909.0,701.0,265.0,610.714286,404.429934,624.071429,385.499768,0
1121,2026-01-29,872,3,1,5,930.0,796.0,853.0,674.0,10.0,621.571429,411.196570,625.428571,386.400094,0
1122,2026-01-30,930,4,1,5,872.0,862.0,898.0,681.0,280.0,631.285714,418.560515,627.714286,388.226823,0
1123,2026-01-31,61,5,1,5,930.0,44.0,114.0,68.0,5.0,633.714286,414.615772,623.928571,393.839378,0

In [59]:
train = df[df['date'] < "2025-07-01"]
test = df[df['date'] >= '2025-07-01']

In [60]:
from xgboost import XGBRegressor

model = XGBRegressor(
    objective="count:poisson",
    n_estimators=420,
    learning_rate=0.06,
    max_depth=2,
    subsample=0.5,
    colsample_bytree=0.9,
    random_state=42
)

In [68]:
model.fit(train[features], train[target])

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.9, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.06, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=2,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=420,
             n_jobs=None, num_parallel_tree=None, ...)

In [70]:
preds = model.predict(test[features])

In [72]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(test[target], preds)
print("MAE:", mae)

MAE: 82.58348295823583